services:
    # Web Server Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
            - dpg-cr5g5g3v2p9s73agode0-a

    #Database Service
    dpg-cr5g5g3v2p9s73agode0-a:
        image: postgres
        container_name: postgres
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}

    # Application Service
    app:
        container_name: crowdfunding
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - dpg-cr5g5g3v2p9s73agode0-a
        expose:
            - "9000"

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgAdmin
        ports:
            - "5050:80"
        depends_on:
            - dpg-cr5g5g3v2p9s73agode0-a
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
