services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: composer install --optimize-autoloader --no-dev
    startCommand: service nginx start && php-fpm
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
    port: 80
